title: Nathan Austin 
logo: "/images/profile.jpg" 
description: > 
  Dynamic, highly motivated data science professional with a diverse skill set and a passion for driving results. 
  <br><br>
  Background in Environmental science, Engineering, and entrepreneurial business growth and development.
  Strength in ability to understand complex data and communicate it to both technical and non-technical audiences.

  <br><br>
  <a href="https://www.linkedin.com/in/nathaustin">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
